### ISSUE TITLE
doubt with content

### ISSUE THREAD

**Issue by gallegonovato** [nickspaargaren/no-google#114]
Good afternoon @nickspaargaren

First of all wish you a VERY GOOD YEAR 2022.

AND MILLIONS OF THANKS FOR YOUR WORK AND EFFORT. 

I happened to be looking at your non-google source. And I found https://github.com/nickspaargaren/no-google/blob/8c98a3e151e87d216a00574f08e802f72aa4b631/unbound-blocklist-google.conf o https://raw.githubusercontent.com/nickspaargaren/no-google/master/unbound-blocklist-google.conf

And a question arises in my mind. What would the link be valid for. Would it be valid for ublock or adaway for example?.

Best regards and thanks for your time.

**Comment by nickspaargaren** [comment]
HAPPY NEW YEAR!

This list is the result of https://github.com/nickspaargaren/no-google/issues/67 (Create a blocklist for unbound dns.)
https://www.nlnetlabs.nl/projects/unbound/about/
