### ISSUE TITLE
suggestion and/or question

### ISSUE THREAD

**Issue by gallegonovato** [nickspaargaren/no-google#125]
good afternoon @nickspaargaren 

First of all thank you very much for all your time and patience with me. I was thinking about something and a doubt arose. 

and I would like to know what you think of it. It turns out that the gafam files (if I'm not mistaken, it would be to avoid: Google (G), Amazon (A), Facebook (F), Apple (A), Microsoft (M). But we would not be fulfilling the essence of GAFAM, since we are on Github. And this platform is from Microsoft. 

So wouldn't it be better to use: Codeberg, Gitea for example for what would be the spirit of GAFAM? And I don't know if I could create entries to avoid Facebook, and others?. 

Thank you very much for all your time and help.

PD: I thought it helped him more. I'm sad as according to https://github.com/nickspaargaren/no-google/graphs/contributors I only made 56 added and 29 removed entries. Jolin thought it was more useful to him...

**Comment by nickspaargaren** [comment]
Thank you, I am aware but I'm not interested at the moment.
