### ISSUE TITLE
Unbound no longer launches with the list enabled

### ISSUE THREAD

**Issue by Bundy01** [nickspaargaren/no-google#157]
Hi,

Unbound no longer launches with the list enabled. The automated lists do not contain domains on the last two lines, which creates an error in Unbound and it refuses to restart.

This is due to the category `jibemobile*`.

Please remove these two lines.

**Comment by nickspaargaren** [comment]
Hi @Bundy01, thanks for the update. Looks like the following is creating the issue.

`local-zone: "" always_refuse`

Working on it right now.

**Comment by nickspaargaren** [comment]
Looks like I broke the lists yesterday in 6b5e7d8d15268aa9ff4c8746d60181dde96cd0bb. Fixed and I updated the automated scripts to prevent this in the future, thanks again!

**Comment by Bundy01** [comment]
Yes, yesterday there was no problem.
Thanks for your reactivity and for this list :)
