### ISSUE TITLE
Pihole-google-adguard alternative blocklist

### ISSUE THREAD

**Issue by Piber0** [nickspaargaren/no-google#163]
Create a new blocking list based on `pihole-google-adguard.txt` but adding `$important` after each `^` (for example: `||google.com^$important`) to increase the priority of the blocking and avoid the white rules of other blacklists.

**Comment by nickspaargaren** [comment]
Hi @Piber0, thanks for the suggestion! There are probably people that whitelist YouTube for example. If we are going to do this, there will be a seperate blocklist like `pihole-google-adguard-important.txt`.

Docs: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#important-modifier

**Comment by Piber0** [comment]
Yeah for sure, it would be perfect. Also Adguard and uBlock (regarding ad blockers) and Adguard Home (on the DNS blocking side) support this syntax.

Adguard doc: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#important-modifier
uBlock doc: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#important
Adguard doc: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#important

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/163#issuecomment-1311805875

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/163#issuecomment-1401299000

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/163#issue-1442157646

**Comment by nickspaargaren** [comment]
Hi @Piber0, done! Let me know if this works for you!

New list: https://github.com/nickspaargaren/no-google/blob/master/pihole-google-adguard-important.txt

**Comment by Piber0** [comment]
Yes perfectly, thanks !
