### ISSUE TITLE
Domains update (Android 11)

### ISSUE THREAD

**Issue by QuickJack** [nickspaargaren/no-google#164]
I found the following domains on Android 11 which are currently not included in any of the no-google lists:

```
General:
optimizationguide-pa.googleapis.com
pai.googlezip.net

Android:
crashlyticsreports-pa.googleapis.com
voilatile-pa.googleapis.com
```

**Comment by nickspaargaren** [comment]
Thanks and looks good to me, if you have any suggestions, let me know!

**Comment by Kamika242** [comment]
Does anyone know what is voilatile-pa.googleapis.com for? Can't find anything in the net. Thanks!
