### ISSUE TITLE
Question: Which google domain(s) to sign in to nuts.com account?

### ISSUE THREAD

**Issue by Walnutty** [nickspaargaren/no-google#167]
I have the No Google enabled on NextDNS.

Would anyone be able to tell me which domain(s) I need to add to the Allowlist to be able to sign in?

https://nuts.com/sign/in

![Screen Shot 2023-01-08 at 1 40 28 PM](https://user-images.githubusercontent.com/122238397/211225812-5d1f076e-ad3b-4116-9b2c-5a36fe7e3c94.png)

**Comment by nickspaargaren** [comment]
Hi @Walnutty, you can use the network activity tab in the dev tools of any browser to list the domains a website uses, see https://developer.chrome.com/docs/devtools/network/ for more details. (The irony, probably chrome.com is blocked.)

**Comment by Walnutty** [comment]
The actual google.com domain is required to sign in. It's not possible to block Google and sign in because nuts.com uses the Google platform.
