### ISSUE TITLE
Update reame with new Microsoft lists

### ISSUE THREAD

**Issue by nickspaargaren** [nickspaargaren/no-google#180]
Originally posted by @gallegonovato in https://github.com/nickspaargaren/no-google/pull/179#issuecomment-1613885286
 
> One thing I just realized. The links that I had put for Microsoft, are more current than those of jmdugan.
> 
> Since the ones I posted for Narsil. This one hates all weird connections and hates Microsoft.
> 
> And jmdugan's have not been updated for 3 years, you can see it at: https://github.com/jmdugan/blocklists/tree/master/corporations

**Comment by gallegonovato** [comment]
Good afternoon @nickspaargaren

It's just that the lists I posted before are more up to date.

For example we have more updated:

https://github.com/mullvad/dns-blocklists/tree/main/lists/doh/privacy
https://github.com/mullvad/dns-blocklists/tree/main/lists/relay/privacy
https://codeberg.org/Narsil/hosts/src/branch/master/Microsoft/Microsoft
https://codeberg.org/Narsil/hosts/src/branch/master/Microsoft/SpyMicrosoft


A hug

**Comment by nickspaargaren** [comment]
Can't find a better one at the moment. If there is a more recent one available, we should update the readme.
