### ISSUE TITLE
New domains

### ISSUE THREAD

**Issue by koebiii** [nickspaargaren/no-google#187]
Hi!

I have captured the following domains while installing sandboxed Google Play Services on a Google Pixel mobile phone running clean (no additional apps installed at that time) Graphene OS:

business.google.com
market.android.com
app.goo.gl
one.google.com
g.co
wallet.google.com
proofing.upgradeparty.goog
simtransfer.goog
cert-wallet.apple.com (interesting...)
pay.sandbox.google.com
pay.google.com
gds.google.com
play.google.com
enterprise.google.com
near.by
digitalkeypairing.org
wallet.apple.com (again, interesting...)
walletshare.googleapis.com
proofing.gmsdrops.goog
staging-walletshare.sandbox.googleapis.com
www.googleapis.com

I believe that the following domains are currently not covered by the blocklist:

proofing.upgradeparty.goog
simtransfer.goog
near.by
walletshare.googleapis.com
proofing.gmsdrops.goog
staging-walletshare.sandbox.googleapis.com

**Comment by nickspaargaren** [comment]
Thanks @koebiii, great additions!

**Comment by fedupfreddy** [comment]
How do you get this off a phone
