### ISSUE TITLE
New possible domains

### ISSUE THREAD

**Issue by nickspaargaren** [nickspaargaren/no-google#197]
### Context

New possible domains by @gallegonovato

### Domains

googletraveladservices-cn.com
analytics-alv.google.com
googletagservices-cn.com
adstransparency.google.com
adwords.corp.google.com
googleads.github.io
googleads.googleapis.com
newsinitiative.withgoogle.com
pagead.l.google.com
pagead-googlehosted.l.google.com
partnerad.l.google.com
pagead-tpc.l.google.com
partnerdataingestion.googleapis.com
static-doubleclick-net.l.google.com
ampcid.google
analytics.clients6.google.com
analytics.corp.google.com
bigquery.googleapis.com
businessprofileperformance.googleapis.com
cloudaudit.googleapis.com
cloudprofiler.googleapis.com
crashlytics2.l.google.com
firebaseappdistribution.googleapis.com
jmt17.google.com
kmsinventory.googleapis.com
looker.com
looker.googleapis.com
managedidentities.googleapis.com
networkmanagement.googleapis.com
pulse-tracker.corp.google.com
ssl-google-analytics.l.google.com
embeddedassistant.googleapis.com
aiplatform.googleapis.com
contactcenterinsights.googleapis.com
contentwarehouse.googleapis.com
deepmind.google.*
language.googleapis.com
ml.googleapis.com
retail.googleapis.com
videointelligence.googleapis.com
vision.googleapis.com
ads-api.x.com
footprint.network
footprint.network.cdn.cloudflare.netautograph.services.mozaws.net
content-signature-2.cdn.mozilla.net
content-signature-chains.prod.webservices.mozgcp.net
firefox.settings.services.mozilla.com
firefox-settings-attachments.cdn.mozilla.net
remote-settings.nonprod.webservices.mozgcp.net
remote-settings.prod.webservices.mozgcp.net
remote-settings-dev.allizom.org
apps.grapheneos.org
dl.vanadium.app
update.vanadium.app
aus4-admin.mozilla.org
aus5.mozilla.org
balrog.nonprod.cloudops.mozgcp.net
balrog.prod.cloudops.mozgcp.net
balrog.services.mozilla.com
balrog-aus4-admin.r53-2.services.mozilla.com
balrog-aus5.r53-2.services.mozilla.com
balrog-admin-static-stage.stage.mozaws.net
balrog-admin-static-prod.prod.mozaws.net
ntp.netnod.se
nts.netnod.se
sptime.se
time.apple.com
time.g.aaplimg.com
time.cloudflare.com
time.grapheneos.org
time.microsoft.com
time.nl
time.system76.com
time.windows.com
twc.trafficmanager.netautograph.services.mozaws.net
remotedesktop-pa.googleapis.comgcdn.2mdn.net
footprint.network.cdn.cloudflare.net
tracking.carrierlogistics.com
adssettings.google.pt
googleadapis.com
googleads.com
googleads-cn.com
ogads-pa.clients6.google.com
google--analytics-com.cdn.ampproject.org
myadcenter.google.com
locationhistory-pa.googleapis.com
locationhistoryaggregates-pa.googleapis.com
baseremoteconfig.googleapis.comadometry.com
appsgrowthpromo-pa.googleapis.com
businessmessages.google.com
*-chromecontentsuggestions-pa.googleapis.com
chromecontentsuggestions-pa.googleapis.com
content-partnersbadge-pa.googleapis.com
exploresites-pa.googleapis.com
gapromomanager-pa.googleapis.com
feedserver-enterprise.googleusercontent.com
gsacollections-pa.googleapis.com
gstaticadssl.l.google.com
jmt17.google.*
partner-android.appspot.com
s0-2mdn-net.l.google.com
searchpromo-pa.googleapis.com
xgapromomanager-pa.googleapis.com
analyticssuitefrontend-pa.googleapis.com
*-android-context-data.googleapis.com
baseremoteconfig.googleapis.com
clienttracing-pa.googleapis.com
datastream.googleapis.complusone.google.com
2mdn-cn.net
adexchangebuyer.googleapis.com
adexchangebuyer-json.googleapis.com
admob.com.akadns.net
adwords.google
adwords-community.com
adwordsexpress.com
affiliate-script-pr.firebaseapp.com
afs.googleusercontent.com
imgpop.googlecode.com
invoice.googleapis.com
localservices.googleapis.com
mapsbooking.googleapis.com
marketingplatformadmin.googleapis.com
merchantapi.googleapis.com
mybusinesslodging.googleapis.com
mybusinessnotifications.googleapis.com
partnerdev-mapsbooking.googleapis.com
partners.googleapis.com
partners-json.googleapis.com
playmoviesdfe-pa.googleapis.com
reseller.googleapis.com
salefile.googlecode.com
shoppingcontent.googleapis.com
surveys.googleapis.com
syndicatedsearch.goog
travelpartner.googleapis.com
analytics.firebaseapp.com
analytics.googleapis.com
analytics.googleblog.com
analytics-google.org
analyticsadmin.googleapis.com
analyticsdata.googleapis.com
analyticshub.googleapis.com
analyticsinsights-pa.googleapis.com
analyticsmobile-pa.googleapis.com
analyticsreporting.googleapis.com
analyticssearch-pa.googleapis.com
admin.googleapis.com
airdroid.com
deviceenrollmentforwindows.googleapis.com
devicemanagementforwindows.googleapis.com
familylink.google.com
intune.microsoft.com
licensing.googleapis.com
orgpolicy.googleapis.com
osconfig.googleapis.com
policyremediator.googleapis.com
remotebuildexecution.googleapis.com
remotedesktop-pa.googleapis.com
serviceconsumermanagement.googleapis.com
smartdevicemanagement.googleapis.com
zerotouch.googleapis.com

**Comment by koebiii** [comment]
rr3---sn-i5heen7d.gvt1.com

**Comment by tj-commits** [comment]
Why are the following domains here:
 time.nl, time.microsoft.com, time.apple.com, time.windows.com, intune.microsoft.com, time.g.aaplimg.com, time.cloudflare.com, time.grapheneos.org, footprint.network
footprint.network.cdn.cloudflare.netautograph.services.mozaws.net
content-signature-2.cdn.mozilla.net
content-signature-chains.prod.webservices.mozgcp.net
firefox.settings.services.mozilla.com
firefox-settings-attachments.cdn.mozilla.net
remote-settings.nonprod.webservices.mozgcp.net
remote-settings.prod.webservices.mozgcp.net
remote-settings-dev.allizom.org
apps.grapheneos.org
dl.vanadium.app
update.vanadium.app
aus4-admin.mozilla.org
aus5.mozilla.org
balrog.nonprod.cloudops.mozgcp.net
balrog.prod.cloudops.mozgcp.net
balrog.services.mozilla.com
balrog-aus4-admin.r53-2.services.mozilla.com
balrog-aus5.r53-2.services.mozilla.com
balrog-admin-static-stage.stage.mozaws.net
balrog-admin-static-prod.prod.mozaws.net
ntp.netnod.se
nts.netnod.se
sptime.se
time.system76.com
twc.trafficmanager.netautograph.services.mozaws.net
remotedesktop-pa.googleapis.comgcdn.2mdn.net
footprint.network.cdn.cloudflare.net
tracking.carrierlogistics.com

None of these look at all like Google domains. Windows and Microsoft and Apple and Mozilla and Cloudflare are not Google.

**Comment by nickspaargaren** [comment]
Thanks @tj-commits for the heads-up! I tried my best to carefully remove all domains that are not Google's from adding to the list. See merge commit: https://github.com/nickspaargaren/no-google/commit/8f5354cd41009b7d0a0f88e09adb4f59ad8b06e9

If you notice some domains that i missed, we would love to remove these from the list of course!
