### ISSUE TITLE
New List for Facebook/Meta

### ISSUE THREAD

**Issue by Bundy01** [nickspaargaren/no-google#218]
Hi,

@nickspaargaren, the facebook lists you put in the README are not maintained and the repo [https://github.com/lightswitch05/hosts](https://github.com/lightswitch05/hosts) is now archived.

I take over a blocklist for meta inc.
Do you authorize me to add the link to the README?

Regards.

**Comment by nickspaargaren** [comment]
Hi @Bundy01, sure! Can you create a pull request replacing the https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/facebook-extended.txt link with yours?
