### ISSUE TITLE
Maybe change the name to be... less generic ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nickspaargaren/no-google#25]
Nothing really wrong in itself by naming it ¨pihole-google¨, but while I was suggesting to add this to filter list repo's (See #13) i’ve noticed that by the name alone, this could be tought as being one sort of pi-hole default filter, or one that CAN ONLY be used on Pi-hole ~~(Otherwise, uBlock Origin explode or somethin´)~~
Also, comes the fact that Pi-hole is a trademark in itself. https://pi-hole.net/trademark-rules-and-brand-guidelines
In the way we use it, I think it isn’t an issue, but this could be a great idea to actually rename it, as it's starting to became more and more popular with other people, including non-pihole users.
[In one repo](https://github.com/nextdns/lists/pull/13), I’ve suggested using the name ¨No G¨ (But, by precising that it could be nice if they accept to endorse using our ¨actual¨ name for the moment, aka pihole-google).
But I let you see if you are actually agreeing on it @nickspaargaren and if the community would accept the same too.

**Comment by PoorPocketsMcNewHold** [comment]
@nickspaargaren I’m taking the ability to re-mention you, as we are now working on an Amazon blocklist.
Our list is currently registered on NextDNS as No-G (But, still conserve the pihole-google name, on filterlists.com)
So, if you want to stay with the pihole* type of name, I just wanted a confirmation, before pull-requesting the name change on NextDNS website.

If we are still, more incline to change the name, Naming it according to the No-* pattern, It will shortly become limited (Obviously, by the presence of two A in GAFAM).
We can still keep that, with instead No-*company-name instead, as simple it is, It does work, even for someone who doesn’t know about the Pi-hole project.

**Comment by nickspaargaren** [comment]
@PoorPocketsMcNewHold Thank you. Let's go with your advice. So 'no-google'/'no-amazon' instead of 'pihole-google'/'pihole-amazon'? The NextDNS mention is amazing by the way! When agreed, I'll change te names!

**Comment by PoorPocketsMcNewHold** [comment]
Yep, that's the idea.
Of course, if you have another idea, feel free to, but I think it should work well like that already.

**Comment by nickspaargaren** [comment]
Changed it, looks great! Thank you!
