### ISSUE TITLE
Your Google list doesn't block these

### ISSUE THREAD

**Issue by itsmat32143** [nickspaargaren/no-google#32]
This list is epic thank you for all you work making it i have found that your list doesn't block theses domains from google :-)

digitalassetlinks.googleapis.com
app-measurement.com
alt1-mtalk.google.com
alt2-mtalk.google.com
alt3-mtalk.google.com
alt4-mtalk.google.com
alt5-mtalk.google.com
alt6-mtalk.google.com
alt7-mtalk.google.com
alt8-mtalk.google.com

thank you

**Comment by PoorPocketsMcNewHold** [comment]
Sorry for the long answer, I tend to get lost in the GitHub notifications/e-mails and had issued on my main computer. Will add those right now, thanks!

**Comment by PoorPocketsMcNewHold** [comment]
Done ! Added 4ae8f3a & 3357022.

**Comment by itsmat32143** [comment]
hey sorry to be a pain again just really interested in this list didn't want to open a new issue so thats why i am messaging here i have found some more that is not in the list sorry for being such a pain haha

footprints-pa.googleapis.com
realtimesupport.clients6.google.com
cryptauthenrollment.googleapis.com
settings.crashlytics.com
firebaseremoteconfig.googleapis.com
lens-storage.storage.googleapis.com

**Comment by PoorPocketsMcNewHold** [comment]
You are totally welcome. Feel free to even push your pull requests to the repo. Will add it.
Btw, about your last comment, `alt8-mtalk.google.com` was already listed in the filter (But not the previous same domains for some reasons).

**Comment by PoorPocketsMcNewHold** [comment]
Updated in commit 33058ab Would you like this issue open for future domains suggestions, prefer to remain it closed until further activity, or would you prefer pushing pull-requests?

**Comment by itsmat32143** [comment]
I use the list daily and the every now and again scroll through the logs to find ones it has missed i am new here so haven't got a clue about most stuff only know the basics i will learn to do the pull requests and submit any i find that way i can only find a google and amazon list is there a Facebook , Apple and Microsoft or have they not been made yet ??

**Comment by PoorPocketsMcNewHold** [comment]
I’ll let that one open then.
>  i can only find a google and amazon list is there a Facebook , Apple and Microsoft or have they not been made yet ??

We only directly maintain also another Amazon list, and yes, those have not been made yet, but we are planning too.

**Comment by nickspaargaren** [comment]
Added in #34
