### ISSUE TITLE
Some Regex Rules Would Block Non-Google Sites

### ISSUE THREAD

**Issue by bnkas** [nickspaargaren/no-google#33]
Hi there,

I was reading through your regex filters and two rules jumped out that will block popular non-Google sites.

((.).)?abc.(.)
This would block popular TV channel in the US that Disney owns: abc.com. I know Google owns tens of domains with abc in the domain name, but I wanted to point out abc.com as unintended consequence. 

((.).)?android.(.)
This would block popular domains that have the word android in them, for example: www.androidauthority.com that I can easily think of. 

Hopefully you find this helpful if these aren't known previously. 

Thanks

**Comment by PoorPocketsMcNewHold** [comment]
That's indeed problematic. I’ll remove those from the listed regex filters until an equivalent regex filter is created.

**Comment by Jecaperexaa** [comment]
https://github.com/nickspaargaren/no-google/issues/33#issuecomment-640010557
