### ISSUE TITLE
Add 1e100.net to the list

### ISSUE THREAD

**Issue by varistov** [nickspaargaren/no-google#42]
[What is 1e100.net?](https://support.google.com/faqs/answer/174717)
[What is 1e100.net and why do I have TCP ports open to it?](https://superuser.com/questions/75841/what-is-1e100-net-and-why-do-i-have-tcp-ports-open-to-it)

**Comment by PoorPocketsMcNewHold** [comment]
Will do, Thanks for your suggestion !

**Comment by PoorPocketsMcNewHold** [comment]
Well, we already had it in fact in the list since a long time. I´ve tought you would have searched it already. Closing it.
