### ISSUE TITLE
Make our two repos, comply to the hacktoberfest event.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nickspaargaren/no-google#44]
https://hacktoberfest.digitalocean.com

The current DigitalOcean x GitHub FOSS event is currently live, and require repositories, to opt-in, to prevent [some unwanted spam and repo sabotage pull requests](https://nitter.snopyta.org/shitoberfest).

https://viewtube.io/watch?v=FxBv4FMcDgo (YouTube video link, also available at youtube\[dot\]com/watch?v=FxBv4FMcDgo)

https://hacktoberfest.digitalocean.com/details#maintainers

**Comment by nickspaargaren** [comment]
Added, thanks! Will add more relevant labels soon. Any suggestions?

**Comment by PoorPocketsMcNewHold** [comment]
Related to it, not that I think of. I don’t think a CONTRIBUTING.md file need to be done, and I’ll try to handle myself if they are any spam/low-quality submissions coming out this month.

Outside that, I think I’m going to do some overhaul cleaning and some general aesthetics change to the repo organization, I’ll create a pull request to review it when it’s done.
