### ISSUE TITLE
[Feature Request] Whitelist to make Google Services work

### ISSUE THREAD

**Issue by eggplanting** [nickspaargaren/no-google#45]
Hello,

I'm using your "No Google" Blocklist with Pi-Hole and really like what it does. As expected, I had to whitelist many services to get my Android smartphones working with the usual Google apps (Play Store, Maps, etc.).

It would be great if you could add an additional whitelist which enables Google Services but only with the minimal amount of needed domains to work. A few examples:
- Google Fonts: fonts.google.com, fonts.googleapis.com, fonts.gstatic.com
- Youtube: www.youtube.com, i.ytimg.com, s.ytimg.com, etc.
- Google Play Store on Android: play.google.com, play.googleapis.com

Your whitelist would be optional to users who want to use Google services with less tracking.

Would be great to know what you think. Thanks a lot for this project so far!

**Comment by itsmat32143** [comment]
To My Knowledge this is already sort of done can you not use the files in categories to unblock YouTube and fonts ??

I do not think there is a google play store one there is just one for google products but i could knock a list up for that easily if allowed 👍

Let me know how you get on ✌

**Comment by PoorPocketsMcNewHold** [comment]
I’m thinking of actually using #46 to add potential domains to whitelist to troubleshoot it, and potential problematic services with those.

I might be making a fork of https://github.com/anudeepND/whitelist with a list of common whitelist as you say, but I think pihole user would already know how to whitelist selected domains individually.

Feel free to use this issue to suggest domains to whitelist, or methods to bypass it, like LocalCDN for CDN´s, or invidious for Youtube for example.

**Comment by eggplanting** [comment]
Thanks for the suggestions, a whitelist for Pi-Hole would be exactly what I'm looking for.

It would be easy to add the No Google blicklist together with the whitelist, which would allow only essential DNS requests when Google Services are used. Without telemetry.

Let's see if I can discover some needed URLs for specific services.

**Comment by NSTAdventure** [comment]
@eggplanting bruh then why you using gafam?

aim goal is they purge all 5 company from your life 
so i think (IMO) i useless we are using this while we still relog to google

i currently not using this for a while (My IAP still on google thought :/ )

**Comment by Bundy01** [comment]
I also think we should keep this list intact. It is very comprehensive, if users have URLs that are useful to them, they should be deleted manually or use another more permissive list.

**Comment by nickspaargaren** [comment]
Just as others have answered, you can achieve this with our categories combined with pi-hole's group management tool. The reason I'm mentioning this is because it's quite new to pi hole. Good luck!

@itsmat32143 @PoorPocketsMcNewHold @NSTAdventure and @Bundy01, thank you for your replies!
