### ISSUE TITLE
Add a codensed version with adblock+ syntax

### ISSUE THREAD

**Issue by BirdInFire** [nickspaargaren/no-google#51]
Why asking for this ?

For AdGuard home, where you can do easily add "||metric.gstatic.com^ who will block metric.gstatic.com, but also subdomain.metric.gstatic.com like for instance all xxxxx-dnsotls-ds.metric.gstatic.com with one rules (more efficiant than a hosts/domain based list who have to be regularly updated)

**Comment by PoorPocketsMcNewHold** [comment]
[We already have a list of regex entries for the pi-hole](https://github.com/nickspaargaren/no-google/blob/master/regex.list), but they indeed need to be extended to our current list.
[Same goes for the wildcards root domains](https://github.com/nickspaargaren/no-google/blob/master/wildcards-domains), made for, and used by NextDNS which is a similar DNS service to AdGuard.

**Comment by Macqael** [comment]
regexp is very slow if used with adblock, and wildcar domain in many adblock if you add "google.ad" sor instance it will block "google.ad" but not "something.google.ad".
in adblock syntax the wildcard is "||google.ad^".

**Comment by nickspaargaren** [comment]
Check, I'll assign this to me!
Info: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#introduction-1

**Comment by nickspaargaren** [comment]
@BirdInFire The AdGuard list is live for you to test! Personally I've tested it in de Adguard Pro app and works great!
https://raw.githubusercontent.com/nickspaargaren/no-google/master/pihole-google-adguard.txt

@PoorPocketsMcNewHold The main list is [pihole-google.txt](https://github.com/nickspaargaren/no-google/blob/master/pihole-google.txt) and will create the AdGuard list and category lists automatically on new commits!

**Comment by BirdInFire** [comment]
> @BirdInFire The AdGuard list is live for you to test! Personally I've tested it in de Adguard Pro app and works great! https://raw.githubusercontent.com/nickspaargaren/no-google/master/pihole-google-adguard.txt
> 
> @PoorPocketsMcNewHold The main list is [pihole-google.txt](https://github.com/nickspaargaren/no-google/blob/master/pihole-google.txt) and will create the AdGuard list and category lists automatically on new commits!

thanks will test that ASAP :)
