### ISSUE TITLE
Compare our current list with the automatised jduggan corporation one.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nickspaargaren/no-google#52]
Discovered on Lemmy https://lemmy.ml/post/52950
https://github.com/jmdugan/blocklists/tree/master/corporations/google
I should compare the current list they got, and also, try to found some time to actively maintain our blocklists once again.

**Comment by PoorPocketsMcNewHold** [comment]
From looking at it at first sight. It seems to be far more less complete than our list, due to being just scrapped from a Wikipedia list of Google domains.
Nothing really to get from it, outside of instead, of their build scripts. (As an idea only, especially since we are licensed under a different License)

**Comment by nickspaargaren** [comment]
Actually there are a few we missed, some of them really surprised me. Added, although i still have to order them: https://github.com/nickspaargaren/no-google/commit/1affef816560cfbc454e5924ca525c3998884c3b
