### ISSUE TITLE
Update of categories folder

### ISSUE THREAD

**Issue by QuickJack** [nickspaargaren/no-google#56]
The files in this folder haven't been updated since months. It's nice to have new domains (like https://github.com/nickspaargaren/no-google/issues/50) added to  pihole-google.txt. But when and how are the files in the categories folder updated? This is important if someone doesn't want to block all of Google.

**Comment by nickspaargaren** [comment]
Hi @QuickJack and @PoorPocketsMcNewHold,

Thanks for the reminder! The GitHub stats show that not many people are using the categories at the moment. Only a few people have watched the YouTube category and that's the maximum as far as I can see.

I am working on a script in a [new branch](https://github.com/nickspaargaren/no-google/tree/Automate-categories) that reads the [main file](https://github.com/nickspaargaren/no-google/blob/master/pihole-google.txt) and creates the separate category files automatically. I'm not a Python expert yet, but I'll try to look into it. I hope to build the script, so when the [main file](https://github.com/nickspaargaren/no-google/blob/master/pihole-google.txt) is updated / committed, the script runs on a server(?) and creates / commit the specific category files automatically. At this point, this commit / addition was copy and paste for information.

If you have any ideas or a better plan, let us know!
