### ISSUE TITLE
AIO Host File To Block GAFAM?

### ISSUE THREAD

**Issue by NSTAdventure** [nickspaargaren/no-google#60]
Hey Is Looks Like You Make Separate Host TXT File For Each Company From GAFAM

I Want to get aio version pls? Where in 1 host file included All 5 company (GAFAM)

edit:
also add 0.0.0.0 before domain pls :)

**Comment by nickspaargaren** [comment]
Personally I lean towards separate list because most people will block only one or two companies. It's fairly easy to add a maximum 5 urls right now.

You can find the 0.0.0.0 list here: https://github.com/nickspaargaren/no-google/blob/master/google-domains

**Comment by NSTAdventure** [comment]
> Personally I lean towards separate list because most people will block only one or two companies. It's fairly easy to add a maximum 5 urls right now.
> 
> You can find the 0.0.0.0 list here: https://github.com/nickspaargaren/no-google/blob/master/google-domains

bro apple txt doesn't contain 0.0.0.0 :(

**Comment by nickspaargaren** [comment]
> bro apple txt doesn't contain 0.0.0.0 :(

I'm not following, can you elaborate?
