### ISSUE TITLE
Remove CHEF-KOCH links from readme

### ISSUE THREAD

**Issue by jsuelwald** [nickspaargaren/no-google#61]
The repository on gitlab doesn't exist anymore and should be removed from this repository as well.

Relevant link: https://github.com/arkenfox/user.js/issues/323 "FACT: CHEF-KOCH plagiarizes and passes off other people's work as his own"

**Comment by nickspaargaren** [comment]
Looks like [this account](https://gitlab.com/CHEF-KOCH) is blocked already, otherwise can you elaborate?

**Comment by fabianegli** [comment]
I think the hope was that you remove the links in question from the README.md and  all content that was derived from these linked repos. 

In addition to serious ethical concerns, the links simply don't work anymore. 

Content copied from these repos should be removed from this repository, ideally in favor of content form the repositories which were illegally copied by that account to credit the original sources of the content you distribute.
