### ISSUE TITLE
Duplicates in the google-domains and pihole-google.txt lists.

### ISSUE THREAD

**Issue by Bundy01** [nickspaargaren/no-google#66]
Hello, I found three duplicates in this lists:
- beacons.gcp.gvt2.com
- gcp.gvt2.com
- redirector.gvt1.com

You can check this with the command `sort -g YOUR_LIST|uniq -D`

Otherwise, it's a great list. Thanks for the work done.

Regards.

**Comment by nickspaargaren** [comment]
Thanks @Bundy01 !

**Comment by Bundy01** [comment]
Hi,
I recently downloaded the google-domains list, I found duplicates:

1. connectivitycheck.android.com
2. connectivitycheck.gstatic.com
3. pagead2.googlesyndication.com
