### ISSUE TITLE
Future request: Create a blocklist for unbound.

### ISSUE THREAD

**Issue by Bundy01** [nickspaargaren/no-google#67]
Hi,

It would be interesting to create a list for unbound.
What do you think about it?

Regards.

**Comment by nickspaargaren** [comment]
Hi @Bundy01 , very interesting! Do you mean a format like this? https://raw.githubusercontent.com/k0nsl/unbound-blocklist/master/blocks.conf

local-zone: -> local-data:

How would you use this format? Could you send us some information?

**Comment by Bundy01** [comment]
Hi @nickspaargaren ,

This is to use a blocklist in Unbound (resolver local DNS).
The syntax can be:
```
local-zone: "googleads2.g.doubleclick.net" redirect
local-data: "googleads2.g.doubleclick.net. A 0.0.0.0"
```
or shorter (to be confirmed):
```
local-zone: "googleads2.g.doubleclick.net" static
```
The second solution reduces the number of lines by two :)

**Comment by Prajwal-Koirala** [comment]
> Hi @nickspaargaren ,
> 
> This is to use a blocklist in Unbound (resolver local DNS).
> The syntax can be:
> 
> ```
> local-zone: "googleads2.g.doubleclick.net" redirect
> local-data: "googleads2.g.doubleclick.net. A 0.0.0.0"
> ```
> 
> or shorter (to be confirmed):
> 
> ```
> local-zone: "googleads2.g.doubleclick.net" static
> ```
> 
> The second solution reduces the number of lines by two :)

Does this work?

**Comment by Bundy01** [comment]
Hi,

I found [this](https://wiki.archlinux.org/title/Unbound#Domain_blacklisting).
I converted the file 'google-domains' with this command. So far it works on the tested domains.
`grep '^0\.0\.0\.0' FILE_TO_CONVERT | awk '{print "local-zone: \""$2"\" always_refuse"}' | sudo tee FILE_UNBOUND`

If you are interested in converting hosts files to Unbound blocklists, just type this command and add 'server:' at the beginning of the files :)

Beginning of the converted file:
```
server:
local-zone: "apis.googletagmanager.com" always_refuse
local-zone: "click.google-analytics.com" always_refuse
local-zone: "crashlytics.com" always_refuse
local-zone: "crashlyticsreports-pa.googleapis.com" always_refuse
local-zone: "dr-mobiweb.googleoptimize.com" always_refuse
local-zone: "google-analytics.com" always_refuse
local-zone: "googletagmanager.com" always_refuse
local-zone: "googletagservices.com" always_refuse
local-zone: "htps.googletagmanager.com" always_refuse
```

Regards.

**Comment by amotl** [comment]
Dear @Bundy01 and @nickspaargaren,

54bd8518df7 adds a corresponding routine to the improved output format converter, submitted with #109.

With ind regards,
Andreas.

**Comment by nickspaargaren** [comment]
Sorry @Bundy01, I renamed the file to match the others:
https://github.com/nickspaargaren/no-google/blob/master/pihole-google-unbound.conf
Possibly you need to update the url in your software.

**Comment by Prajwal-Koirala** [comment]
```
local-zone: "htps.googletagmanager.com" always_refuse
local-zone: "httpswww.googletagmanager.com" always_refuse
```

**Comment by nickspaargaren** [comment]
Hi, @Prajwal-Koirala, thanks for your reply, is the list correct this way in your opinion?
