### ISSUE TITLE
Possibility to create a host file?

### ISSUE THREAD

**Issue by gallegonovato** [nickspaargaren/no-google#78]
Good morning:

First of all thank you for your work, your effort, your time and for your lists.

I would like to ask you a question if I may.

I don't know if it would be possible to create a host file, to be able to use your work also with Adaway?

Since for example your source https://raw.githubusercontent.com/nickspaargaren/no-google/master/pihole-google-adguard.txt or with all of https://github.com/nickspaargaren/no-google/tree/master/categories . If you would be so kind to create a hosts file with it, then it could be used for Adaway. And it would be very useful and I would be one of the first to put it. Since I would like to block the things that are included. 

If you are so kind to take into account my consideration and if you can do it, I would appreciate it.

I also take this opportunity to tell you about a possible help for your lists. It would be these hosts: https://gitlab.com/Jorgu81/hosts that I think could help you.

Receive a big hug and thanks for your time. And thank you very much for considering my suggestion.

**Comment by nickspaargaren** [comment]
Hi @gallegonovato Thank you so much for your kind works and your are very welcome!

I would assume [this list](https://github.com/nickspaargaren/no-google/blob/master/google-domains) will work with AdAway. The list points the domains to 0.0.0.0. AdAway wants them to direct them to your internal ip 127.0.0.1 but I think this has the same result. Did you test it with the following file? https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains. If it doesn't work i would of course like to hear back from you!

This list from Gitlab looks like it has a lot of domains that aren't Google's but i will soon scan them and let you know if we'll be able to add them! Of course a pull request on [our main file](https://github.com/nickspaargaren/no-google/blob/master/pihole-google.txt) would be very helpful!

**Comment by gallegonovato** [comment]
Good afternoon @nickspaargaren

Thank you very much for your help and time. I've been using your host for years, but I don't know what's going on lately in Adaway. I have put it back to have if it goes well now. 

The only thing that occurs to me is that the address does not end in .txt as others. Like for example https://adaway.org/hosts.txt

But if it works now or it's from the last version of Adaway.

By the way I do not know what you think as a source for your host: https://raw.githubusercontent.com/ftpmorph/ftpihole/master/blocklists/smartphone-ads-tracking.txt ( https://github.com/ftpmorph/ftprivacy ) , https://github.com/furkun/AndroidSecurityHosts , https://raw.githubusercontent.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts/master/hosts , https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt

Thanks a lot for your help and time.

**Comment by gallegonovato** [comment]
Good afternoon @nickspaargaren

I think I could also help the hosts:

https://github.com/kowith337/PersonalFilterListCollection/tree/master/hosts

https://crapblock.theel0ja.info/

https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/non_localized

https://github.com/furkun?tab=repositories

And maybe some of https://blokada.org/api/v4/content/en/filters.txt (which they have whitelisted)

By the way thank you very much for https://github.com/nickspaargaren/no-google/commit/7cd916204183c11c348ec64b75fb14e50035c599 . But the merit is not mine but Jorgu81's. Then there is a topic to avoid google at https://m.forocoches.com/foro/showthread.php?p=408084444 in case you can help to avoid this company that does nothing but spy on us.

Thank you very much for all your time and help.

**Comment by nickspaargaren** [comment]
Hi @gallegonovato, thanks for your initiative, but all these lists are a bit overwhelming to me. Would you please help us and each other by making separate pull requests in [our main file](https://github.com/nickspaargaren/no-google/blob/master/pihole-google.txt)? We can check and merge the domains, this would be incredibly useful! This way you'll also be on the contributors list and be able to receive fame for life!

Thank you for your time, we really appreciate it! If you have further questions, feel free to reopen this issue!
