### ISSUE TITLE
Problem script regex

### ISSUE THREAD

**Issue by edsonblwolf** [nickspaargaren/no-google#80]
root@pihole:~# curl -sSl https://raw.githubusercontent.com/nickspaargaren/no-google/master/install.sh | bash
[i] Fetching mmotti's regexps
[i] Fetching existing regexps
[i] An error occured whilst fetching results
[i] Checking for previous migration
[i] An error occured whilst fetching results
[i] Previous migration detected
[i] Checking whether updates are required
[i] Running removal query
Error: no such table: regex
[i] An error occured whilst updating database
[i] Generating CSV file
[i] An error occured whilst fetching results
[i] Error: Generated CSV is empty

**Comment by nickspaargaren** [comment]
@PoorPocketsMcNewHold can you please look into this?
