### ISSUE TITLE
Doubt if it is well done

### ISSUE THREAD

**Issue by gallegonovato** [nickspaargaren/no-google#81]
Good afternoon:

First of all apologize if this is not the correct way to contribute new entries to the hosts. But this is the first time I do it this way. So I figured I would screw up, I just hope I didn't screw up to the bottom.

The entries I wanted to propose for the host would be: https://github.com/gallegonovato/no-google/commit/85921a150932754a7e47bc3b77bbcd60a8e35868

I apologize if this is not the right way and I have done something wrong. It wasn't my intention at all, but it's the first time I've done it this way and I probably screwed it up.

So I apologize and I beg your pardon. 

A hug and thank you very much for all your time and help. 

Pd: The entries I wanted to propose are:

0.0.0.0 stats.lineageos.org
0.0.0.0 whitepages.com # Replicant bug, now fixed
## Doubleclick.net
0.0.0.0 1016557.fls.doubleclick.net
0.0.0.0 1268402.fls.doubleclick.net
0.0.0.0 1326154.fls.doubleclick.net
0.0.0.0 1330903.fls.doubleclick.net
0.0.0.0 1742177.fls.doubleclick.net
0.0.0.0 2013561.fls.doubleclick.net
0.0.0.0 2196503.fls.doubleclick.net
0.0.0.0 2332696.fls.doubleclick.net
0.0.0.0 2499034.fls.doubleclick.net
0.0.0.0 2542116.fls.doubleclick.net
0.0.0.0 2793343.fls.doubleclick.net
0.0.0.0 3130320.fls.doubleclick.net
0.0.0.0 3243857.fls.doubleclick.net
0.0.0.0 3276817.fls.doubleclick.net
0.0.0.0 3501113.fls.doubleclick.net
0.0.0.0 3738527.fls.doubleclick.net
0.0.0.0 3773523.fls.doubleclick.net
0.0.0.0 3879194.fls.doubleclick.net
0.0.0.0 3941123.fls.doubleclick.net
0.0.0.0 3973258.fls.doubleclick.net
0.0.0.0 3982178.fls.doubleclick.net
0.0.0.0 4177752.fls.doubleclick.net
0.0.0.0 4191036.fls.doubleclick.net
0.0.0.0 4191748.fls.doubleclick.net
0.0.0.0 4228414.fls.doubleclick.net
0.0.0.0 4235225.fls.doubleclick.net
0.0.0.0 4236808.fls.doubleclick.net
0.0.0.0 4331660.fls.doubleclick.net
0.0.0.0 4338244.fls.doubleclick.net
0.0.0.0 4345210.fls.doubleclick.net
0.0.0.0 4371920.fls.doubleclick.net
0.0.0.0 4375326.fls.doubleclick.net
0.0.0.0 4379742.fls.doubleclick.net
0.0.0.0 8921356.fls.doubleclick.net
0.0.0.0 accounts.doubleclick.net
0.0.0.0 ad-apac.doubleclick.net
0.0.0.0 ad-emea.doubleclick.net
0.0.0.0 pagead3.googlesyndication.com 
## Googleusercontent.com
0.0.0.0 displayads-formats.googleusercontent.com
0.0.0.0 googlehosted.l.googleusercontent.com
0.0.0.0 googleusercontent.com
0.0.0.0 000000000.fls.doubleclick.net
0.0.0.0 00000000.fls.doubleclick.net
0.0.0.0 0000000.fls.doubleclick.net
0.0.0.0 000000.fls.doubleclick.net
0.0.0.0 00000.fls.doubleclick.net
0.0.0.0 0000.fls.doubleclick.net
0.0.0.0 000.fls.doubleclick.net
0.0.0.0 00.fls.doubleclick.net
0.0.0.0 0.fls.doubleclick.net
0.0.0.0 1016557.fls.doubleclick.net
0.0.0.0 1268402.fls.doubleclick.net
0.0.0.0 1326154.fls.doubleclick.net
0.0.0.0 1330903.fls.doubleclick.net
0.0.0.0 1742177.fls.doubleclick.net
0.0.0.0 2013561.fls.doubleclick.net
0.0.0.0 2196503.fls.doubleclick.net
0.0.0.0 2332696.fls.doubleclick.net
0.0.0.0 2499034.fls.doubleclick.net
0.0.0.0 2542116.fls.doubleclick.net
0.0.0.0 2793343.fls.doubleclick.net
0.0.0.0 3130320.fls.doubleclick.net
0.0.0.0 3243857.fls.doubleclick.net
0.0.0.0 3276817.fls.doubleclick.net
0.0.0.0 3501113.fls.doubleclick.net
0.0.0.0 3738527.fls.doubleclick.net
0.0.0.0 3773523.fls.doubleclick.net
0.0.0.0 3879194.fls.doubleclick.net
0.0.0.0 3941123.fls.doubleclick.net
0.0.0.0 3973258.fls.doubleclick.net
0.0.0.0 3982178.fls.doubleclick.net
0.0.0.0 4177752.fls.doubleclick.net
0.0.0.0 4191036.fls.doubleclick.net
0.0.0.0 4191748.fls.doubleclick.net
0.0.0.0 4228414.fls.doubleclick.net
0.0.0.0 4235225.fls.doubleclick.net
0.0.0.0 4236808.fls.doubleclick.net
0.0.0.0 4331660.fls.doubleclick.net
0.0.0.0 4338244.fls.doubleclick.net
0.0.0.0 4345210.fls.doubleclick.net
0.0.0.0 4371920.fls.doubleclick.net
0.0.0.0 4375326.fls.doubleclick.net
0.0.0.0 4379742.fls.doubleclick.net
0.0.0.0 8921356.fls.doubleclick.net
0.0.0.0 3ded44bd838404a6a3f3d7333aa65498.safeframe.googlesyndication.com
0.0.0.0 2c0aabe9-dnsotls-ds.metric.gstatic.com
0.0.0.0 7ecbd5d8-dnsotls-ds.metric.gstatic.com
0.0.0.0 9600015f-dnsotls-ds.metric.gstatic.com
0.0.0.0 ad2.doubleclick.net
0.0.0.0 ad.3au.doubleclick.net
0.0.0.0 adclick.g.doubleclick.net
0.0.0.0 ad-apac.doubleclick.net
0.0.0.0 ad.ae.doubleclick.net
0.0.0.0 ad.ac.doubleclick.net
0.0.0.0 ad.at.doubleclick.net
0.0.0.0 ad.au.doubleclick.net
0.0.0.0 ad.aw.doubleclick.net
0.0.0.0 ad.ax.doubleclick.net
0.0.0.0 ad.be.doubleclick.net
0.0.0.0 ad.br.doubleclick.net
0.0.0.0 ad.ch.doubleclick.net
0.0.0.0 ad.cn.doubleclick.net
0.0.0.0 ad.de.doubleclick.net
0.0.0.0 ad.dk.doubleclick.net
0.0.0.0 ad-emea.doubleclick.net
0.0.0.0 ad.es.doubleclick.net
0.0.0.0 ad.fi.doubleclick.net
0.0.0.0 ad.fr.doubleclick.net
0.0.0.0 ad.il.doubleclick.net
0.0.0.0 ad.in.doubleclick.net
0.0.0.0 ad.jp.doubleclick.net
0.0.0.0 ad.ma.doubleclick.net
0.0.0.0 ad.me.doubleclick.net
0.0.0.0 ad.mo.doubleclick.net
0.0.0.0 ad.nl.doubleclick.net
0.0.0.0 ad.no.doubleclick.net
0.0.0.0 ad.pk.doubleclick.net
0.0.0.0 ad.pl.doubleclick.net
0.0.0.0 ad.ru.doubleclick.net
0.0.0.0 ad.se.doubleclick.net
0.0.0.0 ad.tr.doubleclick.net
0.0.0.0 ad.tw.doubleclick.net
0.0.0.0 ad.ua.doubleclick.net
0.0.0.0 ad.uk.doubleclick.net
0.0.0.0 ad.uk.mo.doubleclick.net
0.0.0.0 ad.ve.doubleclick.net
0.0.0.0 admob.com
0.0.0.0 admob.mobi
0.0.0.0 ads.admob.com
0.0.0.0 ads.youtube.com
0.0.0.0 adservice.google.ae
0.0.0.0 adservice.google.ac
0.0.0.0 adservice.google.at
0.0.0.0 adservice.google.au
0.0.0.0 adservice.google.aw
0.0.0.0 adservice.google.ax
0.0.0.0 adservice.google.be
0.0.0.0 adservice.google.bg
0.0.0.0 adservice.google.br
0.0.0.0 adservice.google.com
0.0.0.0 adservice.google.com.mt
0.0.0.0 adservice.google.co.il
0.0.0.0 adservice.google.co.in
0.0.0.0 adservice.google.co.jp
0.0.0.0 adservice.google.co.ke
0.0.0.0 adservice.google.co.kr
0.0.0.0 adservice.google.co.uk
0.0.0.0 adservice.google.com.eg
0.0.0.0 adservice.google.com.hk
0.0.0.0 adservice.google.com.kw
0.0.0.0 adservice.google.com.mt
0.0.0.0 adservice.google.com.my
0.0.0.0 adservice.google.com.tw
0.0.0.0 adservice.google.com.tr
0.0.0.0 adservice.google.com.ua
0.0.0.0 adservice.google.com.vn
0.0.0.0 adservice.google.ch
0.0.0.0 adservice.google.cl
0.0.0.0 adservice.google.de
0.0.0.0 adservice.google.dk
0.0.0.0 adservice.google.dz
0.0.0.0 adservice.google.es
0.0.0.0 adservice.google.eu
0.0.0.0 adservice.google.fi
0.0.0.0 adservice.google.fr
0.0.0.0 adservice.google.gr
0.0.0.0 adservice.google.hn
0.0.0.0 adservice.google.hr
0.0.0.0 adservice.google.hu
0.0.0.0 adservice.google.ie
0.0.0.0 adservice.google.il
0.0.0.0 adservice.google.in
0.0.0.0 adservice.google.it
0.0.0.0 adservice.google.iq
0.0.0.0 adservice.google.jo
0.0.0.0 adservice.google.jp
0.0.0.0 adservice.google.kz
0.0.0.0 adservice.google.la
0.0.0.0 adservice.google.lk
0.0.0.0 adservice.google.ma
0.0.0.0 adservice.google.me
0.0.0.0 adservice.google.mk
0.0.0.0 adservice.google.mn
0.0.0.0 adservice.google.mv
0.0.0.0 adservice.google.nl
0.0.0.0 adservice.google.no
0.0.0.0 adservice.google.pk
0.0.0.0 adservice.google.pl
0.0.0.0 adservice.google.se
0.0.0.0 adservice.google.ru
0.0.0.0 adservice.google.tr
0.0.0.0 adservice.google.tw
0.0.0.0 adservice.google.ua
0.0.0.0 ad.doubleclick.net
0.0.0.0 adx.g.doubleclick.net
0.0.0.0 ads-bid.l.doubleclick.net
0.0.0.0 ade.googlesyndication.com
0.0.0.0 ampcid.google.com
0.0.0.0 analytics.google.com
0.0.0.0 analytics.admob.com
0.0.0.0 api.admob.com
0.0.0.0 api.crashlytics.com
0.0.0.0 apps.admob.com
0.0.0.0 beacons.gvt2.com
0.0.0.0 beacons2.gvt2.com
0.0.0.0 beacons3.
0.0.0.0 beacons4.gvt2.com
0.0.0.0 beacons5.gvt2.com
0.0.0.0 beacons5.gvt3.com
0.0.0.0 beacons.gcp.gvt2.com
0.0.0.0 broadcast.admob.com
0.0.0.0 buttons.googlesyndication.com
0.0.0.0 b.admob.com
0.0.0.0 c.admob.com
0.0.0.0 c1.vip.sc9.admob.com
0.0.0.0 clk1.vip.sc9.admob.com
0.0.0.0 clk2.vip.sc9.admob.com
0.0.0.0 clk3.vip.sc9.admob.com
0.0.0.0 c122004c-dnsotls-ds.metric.gstatic.com
0.0.0.0 cm.crashlytics.com
0.0.0.0 cpm.admob.com
0.0.0.0 cpm1.admob.com
0.0.0.0 cpm1.vip.sc9.admob.com
0.0.0.0 cpm2.admob.com
0.0.0.0 cpm2.vip.sc9.admob.com
0.0.0.0 cpm3.admob.com
0.0.0.0 cpm3.vip.sc9.admob.com
0.0.0.0 click.google-analytics.com
0.0.0.0 clientmetrics-pa.googleapis.com
0.0.0.0 crashlytics.com
0.0.0.0 crashlyticsreports-pa.googleapis.com
0.0.0.0 crashlytics2.l.google.com
0.0.0.0 c.googlesyndication.com
0.0.0.0 dart.l.doubleclick.net
0.0.0.0 dep.admob.com
0.0.0.0 displayads-formats.googleusercontent.com
0.0.0.0 doubleclick.net
0.0.0.0 e.admob.com
0.0.0.0 e.crashlytics.com
0.0.0.0 firebase-settings.crashlytics.com
0.0.0.0 firebaselogging-pa.googleapis.com
0.0.0.0 ff.doubleclick.net
0.0.0.0 fls.doubleclick.net
0.0.0.0 fundingchoices.google.com
0.0.0.0 gan.doubleclick.net
0.0.0.0 g.admob.com
0.0.0.0 gw.admob.com
0.0.0.0 games.admob.com
0.0.0.0 ge-0-0-1-edge1.sc9.admob.com
0.0.0.0 ge-0-0-43-crs1.sc9.admob.com
0.0.0.0 google-analytics.com
0.0.0.0 googletagmanager.com
0.0.0.0 googletagservices.com
0.0.0.0 geomobileservices-pa.googleapis.com
0.0.0.0 googleadservices.com
0.0.0.0 g.doubleclick.net
0.0.0.0 googleads.g.doubleclick.net
0.0.0.0 googleads2.g.doubleclick.net
0.0.0.0 googleads3.g.doubleclick.net
0.0.0.0 googleads4.g.doubleclick.net
0.0.0.0 googleadapis.l.google.com
0.0.0.0 j.admob.com
0.0.0.0 jp.admob.com
0.0.0.0 k.admob.com
0.0.0.0 kits.crashlytics.com
0.0.0.0 l.admob.com
0.0.0.0 l.doubleclick.net
0.0.0.0 m.doubleclick.net
0.0.0.0 m.admob.com
0.0.0.0 mm.admob.com
0.0.0.0 mmv.admob.com
0.0.0.0 mm1.vip.sc1.admob.com
0.0.0.0 mm1.vip.sc9.admob.com
0.0.0.0 mm104.sc9.admob.com
0.0.0.0 media.admob.com
0.0.0.0 metrics.admob.com
0.0.0.0 metric.gstatic.com
0.0.0.0 mobile-displayads.l.doubleclick.net
0.0.0.0 n.admob.com
0.0.0.0 network.admob.com
0.0.0.0 o.admob.com
0.0.0.0 p.admob.com
0.0.0.0 pt.admob.com
0.0.0.0 p1.vip.sc9.admob.com
0.0.0.0 paix1.sc1.admob.com
0.0.0.0 pagead.l.doubleclick.net
0.0.0.0 pagead-googlehosted.l.google.com
0.0.0.0 pagead2.googlesyndication.com
0.0.0.0 pagead46.googlesyndication.com
0.0.0.0 pagead46.l.doubleclick.net
0.0.0.0 partnerad.l.doubleclick.net
0.0.0.0 partner.googleadservices.com
0.0.0.0 pixel.admobclick.com
0.0.0.0 pubads.g.doubleclick.net
0.0.0.0 q.admob.com
0.0.0.0 r.admob.com
0.0.0.0 ru.admob.com
0.0.0.0 rmd.admob.com
0.0.0.0 rd.intl.doubleclick.net
0.0.0.0 redirector.c.googlesyndication.com
0.0.0.0 reports.crashlytics.com
0.0.0.0 safeframe.googlesyndication.com
0.0.0.0 s.admob.com
0.0.0.0 sc1.admob.com
0.0.0.0 sc9.admob.com
0.0.0.0 smtp.admob.com
0.0.0.0 smtp2.admob.com
0.0.0.0 s0.doubleclick.net
0.0.0.0 s0-2mdn-net.l.google.com
0.0.0.0 s-v6exp1-ds.metric.gstatic.com
0.0.0.0 securepubads.g.doubleclick.net
0.0.0.0 semanticlocation-pa.googleapis.com
0.0.0.0 settings.crashlytics.com
0.0.0.0 ssl.googleanalytics.com
0.0.0.0 ssl.google-analytics.com
0.0.0.0 stats.blogger.com
0.0.0.0 stats.g.doubleclick.net
0.0.0.0 static.doubleclick.net
0.0.0.0 static.googleadsserving.cn
0.0.0.0 supl.google.com
0.0.0.0 tracking.admobsphere.com
0.0.0.0 tic.googlesyndication.com
0.0.0.0 tpc.googlesyndication.com
0.0.0.0 tpc.googlesyndication.com.proxy.c9w.net
0.0.0.0 tpcnc.googlesyndication.com
0.0.0.0 twx.doubleclick.net
0.0.0.0 tx102.sc9.admob.com
0.0.0.0 tx103.sc9.admob.com
0.0.0.0 u.admob.com
0.0.0.0 ukr.admob.com
0.0.0.0 userlocation.googleapis.com
0.0.0.0 v.admob.com
0.0.0.0 vip.sc9.admob.com
0.0.0.0 video-ad-stats.googlesyndication.com
0.0.0.0 video-stats.video.google.com
0.0.0.0 vodads.g.doubleclick.net
0.0.0.0 w.admob.com
0.0.0.0 wap.admob.com
0.0.0.0 waps.admob.com
0.0.0.0 wendy.admob.com
0.0.0.0 whatbrowser.org
0.0.0.0 www-googletagmanager.l.google.com
0.0.0.0 x.admob.com
0.0.0.0 y.admob.com
0.0.0.0 z.admob.com
0.0.0.0 zhcn.admob.com
0.0.0.0 zhru.admob.com
0.0.0.0 zhuk.admob.com
0.0.0.0 zhtw.admob.com
0.0.0.0 www.admob.com
0.0.0.0 www.admob.com.akadns.net
0.0.0.0 www.doubleclick.net
0.0.0.0 www3.doubleclick.net
0.0.0.0 www2.doubleclick.net
0.0.0.0 www1.doubleclick.net
0.0.0.0 www.googleadservices.com
0.0.0.0 www.googleanalytics.com
0.0.0.0 www.google-analytics.com
0.0.0.0 www.googletagmanager.com
0.0.0.0 0-google.com
0.0.0.0 googlanalyticss.club
0.0.0.0 googlemapsupport.com
0.0.0.0 autopush.prod.mozaws.net
0.0.0.0 push.services.mozilla.com
0.0.0.0 gmscompliance-pa.googleapis.com
0.0.0.0 gmbmobile-pa.googleapis.com

**Comment by nickspaargaren** [comment]
Hi @gallegonovato, again, thank you so much for you pull request. Unfortunately i cannot edit your pull request before merging but i left some comments for you! First would you please take a look at our new [contributing file](https://github.com/nickspaargaren/no-google/blob/master/CONTRIBUTING.md). I apologise for sending this after you made your changes and hope that you can look into it. Thank you!

**Comment by gallegonovato** [comment]
Good afternoon @nickspaargaren

I don't know if the contribution is well done or if I have to make it to https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains or follow https://github.com/nickspaargaren/no-google/blob/master/CONTRIBUTING.md.
. Thank you very much for your time and help.

Not if I did the contribution right. Sorry if I did it wrong, but it's the first time for me. And I'm sure I screwed up to the bottom.

So I beg your pardon 

Best regards

**Comment by nickspaargaren** [comment]
hi @gallegonovato, don't worry, you're doing great! A little side note: you don't have to apologise every time, we are extremely happy with your help!

I made the contributing file to explain how contrubutions will be made from now on. Changes will be made in the pihole-google.txt file (please check the file extension.txt). If you make a pull request to the develop branch instead of the master branch, i can make changes to your pull request.

Again, don't apologise and keep doing these pull requests, accept/ask of feedback and learn!

Many thanks!

**Comment by gallegonovato** [comment]
Good afternoon:

I don't know if the contributions are well done.

I join you the links:

https://github.com/nickspaargaren/no-google/pull/85

https://github.com/nickspaargaren/no-google/pull/88

https://github.com/nickspaargaren/no-google/pull/89

https://github.com/nickspaargaren/no-google/pull/90

https://github.com/nickspaargaren/no-google/pull/90

And then: https://github.com/nickspaargaren/no-google/issues/81

Also I have if I can upload some hosts to some online storage without registration of the style of: https://www.redeszone.net/tutoriales/redes-cable/paginas-enviar-archivos-sin-registro/ or https://www.transfernow.net/es of some hosts files with everything from Google to see what you think. Because it does not allow me to upload everything.

Sorry to be so heavy. And I hope I have done things right. And don't send me to .... 

By the way interesting https://github.com/privacy-guides/android-hosts

A hug

**Comment by nickspaargaren** [comment]
Merged! Many thanks and Merry Christmas!
