### ISSUE TITLE
Duplicates in block files

### ISSUE THREAD

**Issue by Bundy01** [nickspaargaren/no-google#86]
Hi,
@nickspaargaren: I recently downloaded the google-domains list, I found duplicates:

1. connectivitycheck.android.com
2. connectivitycheck.gstatic.com
3. pagead2.googlesyndication.com

_Originally posted by @Bundy01 in https://github.com/nickspaargaren/no-google/issues/66#issuecomment-995286511_

**Comment by nickspaargaren** [comment]
Thanks @Bundy01!
